package interfaces

const (
	LOBBY_CREATING = "LOBBY_CREATING"
	LOBBY_CREATED  = "LOBBY_CREATED"
	LOBBY_STARTED  = "LOBBY_STARTED"
	LOBBY_RUNNING  = "LOBBY_RUNNING"
	LOBBY_FINISHED = "LOBBY_FINISHED"
	LOBBY_FAILED   = "LOBBY_FAILED"
)
