api:
  port: 3000
  gracefulShutdownTimeout: 30s

adapters:
  redis:
    poolSize: 500
    uri: "localhost:6379"
    user: ""
    password: ""
    db: 0

  stomp:
    url: "localhost:61613"

lobby:
  maxPlayers: 1