api:
  port: 3000
  gracefulShutdownTimeout: 30s

adapters:
  redis:
    poolSize: 50
    uri: "localhost:6379"
    user: ""
    password: ""
    db: 0

lobby:
  maxPlayers: 1 # use 10 in production

bot:
  allowCheats: true
  # username: "" # Used for tests
  # password: "" # Used for tests

providers:
  aws:
    region: ""
    clusterName: ""
    taskDefinition: ""
    subnet1: ""
    subnet2: ""
    securityGroup: ""